import type { EventCardData } from '@/interfaces/events.interface';

const COMMON_TERMS = [
	'Official tickets available on the district-clone app and authorised channels only. Do not purchase from unauthorised sources — counterfeit tickets will be considered invalid.',
	'Each attendee can buy a maximum of 10 tickets across all categories.',
	'Tickets are non-cancellable and non-refundable.',
	'Rights of admission reserved. Venue rules apply at all times.',
	'Valid government-issued photo ID required for entry.',
	'Outside food and beverages are not permitted inside the venue.',
	'Management reserves the right to refuse entry without explanation.',
];

export const DUMMY_EVENTS: EventCardData[] = [
	{
		id: "e1b2c3d4-0001-0001-0001-000000000001",
		title: "Coldplay: Music of the Spheres World Tour",
		description:
			"An unforgettable night of light, colour and music that spans their entire legendary career. Featuring a spectacular display of LED wristbands, confetti, and stunning visuals.",
		status: "live",
		coverImage: "https://picsum.photos/seed/coldplay1/800/500",
		date: "2026-03-15",
		time: "20:00",
		end_time: "23:30",
		isPromoted: true,
		venue_name: "Jawaharlal Nehru Stadium",
		venue_address: "Jawaharlal Nehru Stadium, Lodhi Road, New Delhi 110003",
		city_name: "Delhi",
		city: "delhi",
		price_min: 2500,
		price_max: 15000,
		currency: "INR",
		is_wishlisted: true,
		event_type: "single_day",
		availability: "filling_fast",
		categories: ["Music", "Performances"],
		subCategory: "concert",
		languages: ["english"],
		amenities: ["Parking", "Food Court", "Restrooms", "First Aid", "Water Station"],
		prohibited_items: ["Outside Food", "Glass Bottles", "Cameras", "Drones"],
		seating_type: "non_seated",
		instagramUrl: "https://instagram.com/coldplay",
		artist_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567801",
		media_images: [
			"https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
			"https://picsum.photos/seed/coldplay1/800/600",
			"https://picsum.photos/seed/coldplay2/800/600",
		],
		venue_distance_km: 8.2,
		schedule_items: [
			{ label: 'Gates open', time: '6:30 PM' },
			{ label: 'Opening act', time: '7:30 PM' },
			{ label: 'Coldplay', time: '8:00 PM' },
			{ label: 'Event ends', time: '11:30 PM' },
		],
		highlights: [
			{ id: 'h1', icon: '🌈', title: 'A spectacle like no other', description: 'LED wristbands, fireworks, and a world-class light show turn the stadium into a canvas.' },
			{ id: 'h2', icon: '🎵', title: 'Career-spanning setlist', description: 'Music spanning 25+ years of Coldplay\'s iconic catalog.' },
		],
		artists_detail: [
			{
				id: 'a_coldplay',
				name: 'Coldplay',
				role: 'British rock band',
				image: 'https://picsum.photos/seed/coldplay_art/400/400',
				bio: 'Coldplay is a British rock band formed in London in 1996. Consisting of Chris Martin, Jonny Buckland, Guy Berryman, and Will Champion, they have sold over 100 million records worldwide. Their Music of the Spheres World Tour is the highest-grossing concert tour of all time.',
				instagramFollowers: '12.4M',
				youtubeSubscribers: '20M',
			},
		],
		about: 'An unforgettable night of light, colour and music spanning their entire legendary career. Featuring a spectacular display of LED wristbands, confetti, and stunning visuals that turn the entire stadium into one massive canvas.\n\nColdplay\'s Music of the Spheres World Tour is the highest-grossing concert tour of all time, and now it\'s coming to India for a once-in-a-lifetime experience.\n\nJoin over 50,000 fans for a show that promises to be truly out of this world.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Event will be in English' },
			{ iconName: 'Users', label: 'All ages welcome' },
			{ iconName: 'Ticket', label: 'Ticket required for ages 3 and above' },
			{ iconName: 'PawPrint', label: 'Pets not allowed' },
			{ iconName: 'Shield', label: 'Security check at entry' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Utensils', label: 'Food court inside' },
			{ iconName: 'Shield', label: 'First aid on site' },
			{ iconName: 'Droplets', label: 'Water stations available' },
			{ iconName: 'CreditCard', label: 'ATM on site' },
		],
		gallery_urls: [
			'https://picsum.photos/seed/coldplay_g1/600/600',
			'https://picsum.photos/seed/coldplay_g2/600/600',
			'https://picsum.photos/seed/coldplay_g3/600/600',
			'https://picsum.photos/seed/coldplay_g4/600/600',
			'https://picsum.photos/seed/coldplay_g5/600/600',
		],
		organiser_detail: {
			name: 'Live Nation India',
			logoUrl: 'https://picsum.photos/seed/livenation/200/200',
			likedPercent: 94,
			hostedEvents: 47,
			hostingMonths: 36,
		},
		faqEntries: [
			{ id: 'f1', question: 'What time do gates open?', answer: 'Gates open at 6:30 PM, 1.5 hours before the show starts at 8:00 PM.' },
			{ id: 'f2', question: 'Is re-entry allowed?', answer: 'No re-entry once you exit the venue.' },
			{ id: 'f3', question: 'Are LED wristbands provided?', answer: 'Yes, LED wristbands are complimentary and will be provided at entry for all ticket holders.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
		sale_timeline: [
			{ id: 'st1', label: 'HSBC Pre-sale', dateRange: 'Fri 27 Feb, 12 PM – Sun 01 Mar, 12 PM', status: 'completed' },
			{ id: 'st2', label: 'General sale', dateRange: 'Sun 01 Mar, 1 PM onwards', status: 'active' },
		],
	},
	{
		id: "e1b2c3d4-0002-0002-0002-000000000002",
		title: "The Phantom of the Opera",
		description:
			"Andrew Lloyd Webber's timeless musical returns with a breathtaking new production. Experience the haunting love story of Christine Daaé and the mysterious Phantom beneath the Paris Opera House.",
		status: "live",
		coverImage: "https://picsum.photos/seed/phantom/800/500",
		date: "2026-04-02",
		end_date: "2026-04-20",
		time: "19:30",
		end_time: "22:00",
		isPromoted: true,
		venue_name: "National Centre for the Performing Arts",
		venue_address: "Nariman Point, Mumbai, Maharashtra 400021",
		city_name: "Mumbai",
		city: "mumbai",
		price_min: 800,
		price_max: 5000,
		currency: "INR",
		is_wishlisted: false,
		event_type: "multi_day",
		availability: "available",
		categories: ["Performances", "Music"],
		subCategory: "musical",
		languages: ["english"],
		amenities: ["Parking", "Restrooms", "Cloakroom", "Wheelchair Access"],
		prohibited_items: ["Outside Food", "Cameras", "Pets"],
		seating_type: "seated",
		instagramUrl: "https://instagram.com/phantomoftheopera",
		artist_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567802",
		media_images: [
			"https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
			"https://picsum.photos/seed/phantom1/800/600",
			"https://picsum.photos/seed/phantom2/800/600",
		],
		venue_distance_km: 4.1,
		multi_day_schedule: [
			{
				date: "2026-04-02",
				label: "Thu, Apr 2",
				items: [
					{ label: "Doors open", time: "6:30 PM" },
					{ label: "Performance begins", time: "7:30 PM" },
					{ label: "Interval", time: "8:45 PM" },
					{ label: "Performance ends", time: "10:00 PM" },
				],
			},
			{
				date: "2026-04-05",
				label: "Sun, Apr 5",
				items: [
					{ label: "Doors open", time: "3:30 PM" },
					{ label: "Matinée begins", time: "4:00 PM" },
					{ label: "Interval", time: "5:15 PM" },
					{ label: "Performance ends", time: "6:30 PM" },
				],
			},
			{
				date: "2026-04-09",
				label: "Thu, Apr 9",
				items: [
					{ label: "Doors open", time: "6:30 PM" },
					{ label: "Performance begins", time: "7:30 PM" },
					{ label: "Interval", time: "8:45 PM" },
					{ label: "Performance ends", time: "10:00 PM" },
				],
			},
			{
				date: "2026-04-12",
				label: "Sun, Apr 12",
				items: [
					{ label: "Doors open", time: "3:30 PM" },
					{ label: "Matinée begins", time: "4:00 PM" },
					{ label: "Interval", time: "5:15 PM" },
					{ label: "Performance ends", time: "6:30 PM" },
				],
			},
			{
				date: "2026-04-16",
				label: "Wed, Apr 16",
				items: [
					{ label: "Doors open", time: "6:30 PM" },
					{ label: "Performance begins", time: "7:30 PM" },
					{ label: "Interval", time: "8:45 PM" },
					{ label: "Performance ends", time: "10:00 PM" },
				],
			},
			{
				date: "2026-04-20",
				label: "Sun, Apr 20 — Closing Night",
				items: [
					{ label: "Doors open", time: "6:00 PM" },
					{ label: "Performance begins", time: "7:00 PM" },
					{ label: "Interval", time: "8:15 PM" },
					{ label: "Performance ends", time: "9:30 PM" },
				],
			},
		],
		highlights: [
			{ id: 'h1', icon: '🎭', title: 'West End production', description: 'Internationally acclaimed cast and crew bring this iconic musical to life.' },
			{ id: 'h2', icon: '🎶', title: 'Live orchestra', description: 'A full 30-piece orchestra performs Andrew Lloyd Webber\'s timeless score live.' },
		],
		artists_detail: [
			{
				id: 'a_phantom',
				name: 'The Phantom Cast',
				role: 'West End Musical Cast',
				image: 'https://picsum.photos/seed/phantom_art/400/400',
				bio: 'The Phantom of the Opera features an internationally acclaimed cast handpicked from the finest theatrical talent across the UK and India. This production is directed by Laurence Connor, the award-winning director behind the recent global revival.',
			},
		],
		about: 'Andrew Lloyd Webber\'s timeless musical returns with a breathtaking new production directed by Laurence Connor.\n\nExperience the haunting love story of Christine Daaé and the mysterious Phantom beneath the Paris Opera House, performed by an internationally acclaimed cast with a live 30-piece orchestra.\n\nThis is the most iconic musical of all time, reimagined for a new generation. Don\'t miss your chance to witness theatrical history.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Performance in English' },
			{ iconName: 'Users', label: 'Recommended for ages 8 and above' },
			{ iconName: 'Clock', label: 'Duration: 2.5 hours including interval' },
			{ iconName: 'PawPrint', label: 'Pets not allowed' },
			{ iconName: 'Camera', label: 'Photography not permitted during performance' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'ShoppingBag', label: 'Cloakroom available' },
			{ iconName: 'Accessibility', label: 'Wheelchair accessible' },
		],
		gallery_urls: [
			'https://picsum.photos/seed/phantom_g1/600/600',
			'https://picsum.photos/seed/phantom_g2/600/600',
			'https://picsum.photos/seed/phantom_g3/600/600',
			'https://picsum.photos/seed/phantom_g4/600/600',
		],
		organiser_detail: {
			name: 'BookMyShow Live',
			logoUrl: 'https://picsum.photos/seed/bookmyshow/200/200',
			likedPercent: 92,
			hostedEvents: 23,
			hostingMonths: 24,
		},
		faqEntries: [
			{ id: 'f1', question: 'What is the duration of the show?', answer: 'The show runs for approximately 2.5 hours including a 20-minute interval.' },
			{ id: 'f2', question: 'Is late entry allowed?', answer: 'Latecomers will only be seated during the interval to avoid disruption to other guests.' },
			{ id: 'f3', question: 'Can I use my phone during the show?', answer: 'Mobile phones must be switched to silent. Photography and video recording are strictly prohibited.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
		sale_timeline: [
			{ id: 'st1', label: 'Early Bird', dateRange: 'Mon 02 Mar, 10 AM – Fri 06 Mar, 11 PM', status: 'completed' },
			{ id: 'st2', label: 'Standard Sale', dateRange: 'Sat 07 Mar, 10 AM onwards', status: 'active' },
		],
	},
	{
		id: "e1b2c3d4-0003-0003-0003-000000000003",
		title: "Kendrick Lamar: Grand National Tour",
		description:
			"The Pulitzer Prize-winning rapper brings his most ambitious live show to the world stage. A career-spanning set featuring dazzling production and his latest critically acclaimed tracks.",
		status: "live",
		coverImage: "https://picsum.photos/seed/hiphop3/800/500",
		date: "2026-05-10",
		time: "21:00",
		end_time: "23:30",
		isPromoted: true,
		venue_name: "DY Patil Stadium",
		venue_address: "Dr. D.Y. Patil Sports Academy, Nerul, Navi Mumbai 400706",
		city_name: "Mumbai",
		city: "mumbai",
		price_min: 2000,
		price_max: 12000,
		currency: "INR",
		is_wishlisted: true,
		event_type: "single_day",
		availability: "sold_out",
		categories: ["Music", "Performances"],
		subCategory: "concert",
		languages: ["english"],
		amenities: ["Parking", "Food Court", "Restrooms", "First Aid", "ATM"],
		prohibited_items: ["Outside Food", "Glass Bottles", "Weapons", "Drones"],
		seating_type: "non_seated",
		artist_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567805",
		media_images: [
			"https://picsum.photos/seed/kendrick1/800/600",
			"https://picsum.photos/seed/kendrick2/800/600",
		],
		venue_distance_km: 18.5,
		schedule_items: [
			{ label: 'Gates open', time: '7:00 PM' },
			{ label: 'Opening act', time: '8:00 PM' },
			{ label: 'Kendrick Lamar', time: '9:00 PM' },
			{ label: 'Event ends', time: '11:30 PM' },
		],
		highlights: [
			{ id: 'h1', icon: '🏆', title: 'Pulitzer Prize winner live', description: 'The only rapper to win a Pulitzer Prize performs his most ambitious show ever.' },
			{ id: 'h2', icon: '🎤', title: 'Grand National production', description: 'A cinematic stage experience unlike any hip-hop show seen before.' },
		],
		artists_detail: [
			{
				id: 'a_kendrick',
				name: 'Kendrick Lamar',
				role: 'Rapper, songwriter, record producer',
				image: 'https://picsum.photos/seed/kendrick_art/400/400',
				bio: 'Kendrick Lamar Duckworth is an American rapper and songwriter. Widely regarded as one of the greatest rappers of all time, he is the first non-classical, non-jazz musician to win the Pulitzer Prize for Music. His Grand National Tour is his most visually and musically ambitious live show to date.',
				instagramFollowers: '18.2M',
				youtubeSubscribers: '15M',
			},
		],
		about: 'The Pulitzer Prize-winning rapper brings his most ambitious live show to India for the first time.\n\nThe Grand National Tour is a career-spanning spectacle featuring dazzling production values, a massive LED stage, and Kendrick\'s latest critically acclaimed material alongside his greatest hits.\n\nThis is not just a concert — it\'s a cultural moment. Don\'t miss the show that critics are calling the greatest hip-hop live experience of the decade.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Performance in English' },
			{ iconName: 'Users', label: 'Recommended for ages 16 and above' },
			{ iconName: 'Ticket', label: 'Ticket required for ages 3 and above' },
			{ iconName: 'PawPrint', label: 'Pets not allowed' },
			{ iconName: 'Shield', label: 'Bag check at entry' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Utensils', label: 'Food court inside' },
			{ iconName: 'Shield', label: 'First aid on site' },
			{ iconName: 'CreditCard', label: 'ATM on site' },
		],
		gallery_urls: [
			'https://picsum.photos/seed/kendrick_g1/600/600',
			'https://picsum.photos/seed/kendrick_g2/600/600',
			'https://picsum.photos/seed/kendrick_g3/600/600',
			'https://picsum.photos/seed/kendrick_g4/600/600',
			'https://picsum.photos/seed/kendrick_g5/600/600',
		],
		organiser_detail: {
			name: 'Live Nation India',
			logoUrl: 'https://picsum.photos/seed/livenation/200/200',
			likedPercent: 94,
			hostedEvents: 47,
			hostingMonths: 36,
		},
		faqEntries: [
			{ id: 'f1', question: 'Are tickets still available?', answer: 'This event is sold out. Check the waitlist section on the app for any returned tickets.' },
			{ id: 'f2', question: 'Can I transfer my ticket to someone else?', answer: 'Tickets are non-transferable. Entry will be matched against the buyer\'s ID.' },
			{ id: 'f3', question: 'What is the bag policy?', answer: 'Small bags (up to 30x20cm) are allowed. All bags are subject to security check at entry.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'sold_out',
		sale_timeline: [
			{ id: 'st1', label: 'Artist Pre-sale', dateRange: 'Mon 10 Feb, 10 AM – Wed 12 Feb, 10 AM', status: 'completed' },
			{ id: 'st2', label: 'General Sale', dateRange: 'Thu 13 Feb, 10 AM – Sun 16 Feb, 11 PM', status: 'completed' },
			{ id: 'st3', label: 'Sold Out', dateRange: 'Mon 17 Feb onwards', status: 'active' },
		],
	},
	{
		id: "e1b2c3d4-0004-0004-0004-000000000004",
		title: "Goa Sunburn Festival 2026",
		description:
			"Asia's largest music festival returns to the beaches of Goa for three days of non-stop electronic music, international DJs, and an unparalleled festival experience.",
		status: "live",
		coverImage: "https://picsum.photos/seed/formula1/800/500",
		date: "2026-12-26",
		end_date: "2026-12-28",
		time: "16:00",
		end_time: "03:00",
		isPromoted: true,
		venue_name: "Vagator Beach Grounds",
		venue_address: "Vagator, North Goa, Goa 403509",
		city_name: "Goa",
		city: "goa",
		price_min: 3500,
		price_max: 12000,
		currency: "INR",
		is_wishlisted: false,
		event_type: "multi_day",
		availability: "filling_fast",
		categories: ["Music", "Fests & Fairs", "Nightlife"],
		subCategory: "music_festival",
		languages: ["english", "hindi"],
		amenities: ["Parking", "Food Court", "First Aid", "Water Station", "Restrooms", "ATM"],
		cover_charge: "",
		prohibited_items: ["Outside Food", "Glass Bottles", "Weapons", "Drones", "Lighters"],
		seating_type: "non_seated",
		instagramUrl: "https://instagram.com/goasunburn",
		artist_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567808",
		media_images: [
			"https://picsum.photos/seed/sunburn1/800/600",
			"https://picsum.photos/seed/sunburn2/800/600",
		],
		venue_distance_km: 2.5,
		schedule_items: [
			{ label: 'Gates open', time: '4:00 PM' },
			{ label: 'Stage 1 opens', time: '5:00 PM' },
			{ label: 'Headliner set', time: '10:00 PM' },
			{ label: 'Festival closes', time: '3:00 AM' },
		],
		highlights: [
			{ id: 'h1', icon: '🌊', title: 'Asia\'s largest music festival', description: 'Three days of non-stop electronic music on Goa\'s iconic Vagator beach.' },
			{ id: 'h2', icon: '🎧', title: '50+ international DJs', description: 'World-class DJ lineup across 5 stages including techno, house, and psytrance.' },
		],
		artists_detail: [
			{
				id: 'a_sunburn_dj1',
				name: 'Martin Garrix',
				role: 'Dutch DJ and record producer',
				image: 'https://picsum.photos/seed/garrix_art/400/400',
				bio: 'Martin Garrix is a Dutch DJ and record producer who has been ranked as the world\'s number one DJ by DJ Mag three times. Known for his progressive house sound, he headlines this year\'s Sunburn as the Saturday night headliner.',
				instagramFollowers: '18.5M',
				youtubeSubscribers: '12M',
			},
			{
				id: 'a_sunburn_dj2',
				name: 'Amelie Lens',
				role: 'Belgian DJ and producer',
				image: 'https://picsum.photos/seed/amelie_art/400/400',
				bio: 'Amelie Lens is a Belgian DJ and producer who has become one of the most influential figures in the techno scene. Her raw, powerful sets have earned her residencies at the world\'s top clubs.',
				instagramFollowers: '4.2M',
			},
		],
		about: 'Asia\'s largest music festival returns to the iconic beaches of North Goa for three days of non-stop electronic music.\n\nSunburn Festival 2026 brings together 50+ world-class international and Indian DJs across 5 stages, delivering house, techno, psytrance, and everything in between.\n\nSet against the breathtaking backdrop of Vagator beach, this is more than a festival — it\'s a pilgrimage for electronic music lovers. Early bird tickets are selling out fast.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Event in English and Hindi' },
			{ iconName: 'Users', label: 'Ages 18 and above only' },
			{ iconName: 'Ticket', label: 'Valid ID required for entry' },
			{ iconName: 'PawPrint', label: 'Pets not allowed' },
			{ iconName: 'Droplets', label: 'Stay hydrated — water stations available' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Utensils', label: 'Food & beverages on sale' },
			{ iconName: 'Shield', label: 'First aid on site' },
			{ iconName: 'Droplets', label: 'Water stations' },
			{ iconName: 'CreditCard', label: 'ATM on site' },
		],
		gallery_urls: [
			'https://picsum.photos/seed/sunburn_g1/600/600',
			'https://picsum.photos/seed/sunburn_g2/600/600',
			'https://picsum.photos/seed/sunburn_g3/600/600',
			'https://picsum.photos/seed/sunburn_g4/600/600',
			'https://picsum.photos/seed/sunburn_g5/600/600',
			'https://picsum.photos/seed/sunburn_g6/600/600',
		],
		organiser_detail: {
			name: 'Sunburn Entertainment',
			logoUrl: 'https://picsum.photos/seed/sunburn_org/200/200',
			likedPercent: 89,
			hostedEvents: 14,
			hostingMonths: 48,
		},
		faqEntries: [
			{ id: 'f1', question: 'Is the festival 18+?', answer: 'Yes, Sunburn Festival is strictly 18+ with valid government ID required at entry.' },
			{ id: 'f2', question: 'Are multi-day passes available?', answer: 'Yes, 3-day passes are available at a discounted price. Single-day passes are also available.' },
			{ id: 'f3', question: 'Is re-entry allowed?', answer: 'Re-entry is allowed with a valid wristband. Lost wristbands cannot be replaced.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
		sale_timeline: [
			{ id: 'st1', label: 'Wristband Pre-sale', dateRange: 'Fri 01 Aug, 12 PM – Sun 31 Aug, 12 PM', status: 'completed' },
			{ id: 'st2', label: 'Early Access', dateRange: 'Mon 01 Sep, 12 PM – Sun 30 Sep, 12 PM', status: 'completed' },
			{ id: 'st3', label: 'General Sale', dateRange: 'Wed 01 Oct, 12 PM onwards', status: 'active' },
		],
	},
	{
		id: "e1b2c3d4-0005-0005-0005-000000000005",
		title: "Taylor Swift: The Eras Tour",
		description:
			"A journey through every musical era of Taylor Swift's record-breaking career. A three-and-a-half-hour spectacle featuring elaborate set changes, costume reveals, and surprise acoustic songs.",
		status: "live",
		coverImage: "https://picsum.photos/seed/taylorswift/800/500",
		date: "2026-06-20",
		time: "19:00",
		end_time: "22:30",
		isPromoted: true,
		venue_name: "Narendra Modi Stadium",
		venue_address: "Motera, Ahmedabad, Gujarat 380005",
		city_name: "Ahmedabad",
		city: "ahmedabad",
		price_min: 4000,
		price_max: 25000,
		currency: "INR",
		is_wishlisted: true,
		event_type: "single_day",
		availability: "sold_out",
		categories: ["Music", "Performances"],
		subCategory: "concert",
		languages: ["english"],
		amenities: ["Parking", "Food Court", "Restrooms", "First Aid", "Water Station", "ATM"],
		prohibited_items: ["Outside Food", "Glass Bottles", "Cameras", "Drones", "Selfie Sticks"],
		seating_type: "non_seated",
		artist_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567804",
		media_images: [
			"https://picsum.photos/seed/taylor1/800/600",
			"https://picsum.photos/seed/taylor2/800/600",
		],
		venue_distance_km: 5.0,
		schedule_items: [
			{ label: 'Gates open', time: '5:00 PM' },
			{ label: 'Opening acts', time: '6:30 PM' },
			{ label: 'Taylor Swift', time: '7:00 PM' },
			{ label: 'Event ends', time: '10:30 PM' },
		],
		highlights: [
			{ id: 'h1', icon: '✨', title: '10 era journey', description: 'A 3.5-hour show spanning all 10 of Taylor Swift\'s musical eras with full costume changes.' },
			{ id: 'h2', icon: '🎸', title: 'Surprise acoustic songs', description: 'Two surprise acoustic songs performed live — different each night.' },
		],
		artists_detail: [
			{
				id: 'a_taylor',
				name: 'Taylor Swift',
				role: 'Singer-songwriter, record producer',
				image: 'https://picsum.photos/seed/taylor_art/400/400',
				bio: 'Taylor Swift is an American singer-songwriter and one of the best-selling music artists of all time with over 200 million records sold worldwide. The Eras Tour, celebrating her entire musical catalog, became the first concert tour in history to gross over $1 billion.',
				instagramFollowers: '283M',
				youtubeSubscribers: '58M',
			},
		],
		about: 'A journey through every musical era of Taylor Swift\'s record-breaking career — from her country roots to her latest pop anthems.\n\nThe Eras Tour is a 3.5-hour spectacle featuring elaborate set changes, stunning costume reveals, and nightly surprise acoustic songs. Over 200 million fans have already watched this show across the globe.\n\nNow, for the first time ever, Taylor Swift comes to India. This is the most anticipated concert in Indian history.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Performance in English' },
			{ iconName: 'Users', label: 'All ages welcome' },
			{ iconName: 'Ticket', label: 'Ticket required for ages 3 and above' },
			{ iconName: 'Camera', label: 'Professional cameras not allowed' },
			{ iconName: 'PawPrint', label: 'Pets not allowed' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Utensils', label: 'Food court inside' },
			{ iconName: 'Shield', label: 'First aid on site' },
			{ iconName: 'Droplets', label: 'Water stations available' },
			{ iconName: 'CreditCard', label: 'ATM on site' },
		],
		gallery_urls: [
			'https://picsum.photos/seed/taylor_g1/600/600',
			'https://picsum.photos/seed/taylor_g2/600/600',
			'https://picsum.photos/seed/taylor_g3/600/600',
			'https://picsum.photos/seed/taylor_g4/600/600',
			'https://picsum.photos/seed/taylor_g5/600/600',
		],
		organiser_detail: {
			name: 'Live Nation India',
			logoUrl: 'https://picsum.photos/seed/livenation/200/200',
			likedPercent: 94,
			hostedEvents: 47,
			hostingMonths: 36,
		},
		faqEntries: [
			{ id: 'f1', question: 'Is the Eras Tour coming to more cities in India?', answer: 'Currently only Ahmedabad is confirmed. Follow our social media for announcements.' },
			{ id: 'f2', question: 'Can I resell my ticket?', answer: 'Tickets are non-transferable. Resale tickets are not guaranteed valid entry.' },
			{ id: 'f3', question: 'Are selfie sticks allowed?', answer: 'No, selfie sticks and professional cameras are not permitted inside the venue.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'sold_out',
		sale_timeline: [
			{ id: 'st1', label: 'Swifties Pre-sale', dateRange: 'Mon 05 Jan, 10 AM – Tue 06 Jan, 10 PM', status: 'completed' },
			{ id: 'st2', label: 'Capital One Pre-sale', dateRange: 'Wed 07 Jan, 10 AM – Thu 08 Jan, 10 PM', status: 'completed' },
			{ id: 'st3', label: 'General Sale', dateRange: 'Fri 09 Jan, 10 AM – Sun 11 Jan, 11 PM', status: 'completed' },
			{ id: 'st4', label: 'Sold Out', dateRange: 'Mon 12 Jan onwards', status: 'active' },
		],
	},
	{
		id: "e1b2c3d4-0006-0006-0006-000000000006",
		title: "Tomorrowland 2026: India Edition",
		description:
			"The world's greatest electronic music festival lands in India for the first time. Three days, five stages, and 200+ world-class DJs in an immersive festival universe.",
		status: "live",
		coverImage: "https://picsum.photos/seed/tomorrowland/800/500",
		date: "2026-10-09",
		end_date: "2026-10-11",
		time: "14:00",
		end_time: "02:00",
		isPromoted: false,
		venue_name: "Bandra Kurla Complex Grounds",
		venue_address: "Bandra Kurla Complex, Mumbai, Maharashtra 400051",
		city_name: "Mumbai",
		city: "mumbai",
		price_min: 5000,
		price_max: 18000,
		currency: "INR",
		is_wishlisted: false,
		event_type: "multi_day",
		availability: "available",
		categories: ["Music", "Fests & Fairs", "Nightlife"],
		subCategory: "music_festival",
		languages: ["english"],
		amenities: ["Parking", "Food Court", "First Aid", "Water Station", "Restrooms", "Charging Station", "ATM"],
		prohibited_items: ["Outside Food", "Glass Bottles", "Weapons", "Drones", "Lighters"],
		seating_type: "non_seated",
		instagramUrl: "https://instagram.com/tomorrowland",
		artist_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567808",
		media_images: [
			"https://picsum.photos/seed/tomorrowland1/800/600",
			"https://picsum.photos/seed/tomorrowland2/800/600",
		],
		venue_distance_km: 12.0,
		schedule_items: [
			{ label: 'Gates open', time: '2:00 PM' },
			{ label: 'First acts', time: '3:00 PM' },
			{ label: 'Headliner set', time: '10:00 PM' },
			{ label: 'Festival closes', time: '2:00 AM' },
		],
		highlights: [
			{ id: 'h1', icon: '🌍', title: 'World\'s greatest EDM festival', description: 'Tomorrowland comes to India for the very first time with its signature magical productions.' },
			{ id: 'h2', icon: '🎪', title: '5 stages, 200+ artists', description: 'An immersive festival universe with themed stages and world-class production.' },
		],
		artists_detail: [
			{
				id: 'a_tmrw1',
				name: 'Armin van Buuren',
				role: 'Dutch DJ and record producer',
				image: 'https://picsum.photos/seed/armin_art/400/400',
				bio: 'Armin van Buuren is a Dutch DJ, record producer, and remixer. He has been named the world\'s best DJ in the DJ Mag Top 100 DJs poll five times. His trance-infused sets are legendary at Tomorrowland.',
				instagramFollowers: '9.8M',
				youtubeSubscribers: '7M',
			},
		],
		about: 'The world\'s greatest electronic music festival lands in India for the very first time.\n\nTomorrowland India Edition brings the iconic Belgian festival\'s signature magical productions, fairy-tale stages, and world-class DJ lineup to Mumbai for three unforgettable days.\n\nWith 5 stages, 200+ artists, and over 50,000 festivalgoers, this is a moment of history for Indian music culture. Welcome to tomorrow.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Event in English' },
			{ iconName: 'Users', label: 'Ages 18 and above only' },
			{ iconName: 'Ticket', label: 'Valid ID required for entry' },
			{ iconName: 'PawPrint', label: 'Pets not allowed' },
			{ iconName: 'Zap', label: 'Charging stations available' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Utensils', label: 'Food & beverages on sale' },
			{ iconName: 'Shield', label: 'First aid on site' },
			{ iconName: 'Droplets', label: 'Water stations' },
			{ iconName: 'Zap', label: 'Charging stations' },
			{ iconName: 'CreditCard', label: 'ATM on site' },
		],
		gallery_urls: [
			'https://picsum.photos/seed/tmrw_g1/600/600',
			'https://picsum.photos/seed/tmrw_g2/600/600',
			'https://picsum.photos/seed/tmrw_g3/600/600',
			'https://picsum.photos/seed/tmrw_g4/600/600',
		],
		organiser_detail: {
			name: 'ID&T India',
			logoUrl: 'https://picsum.photos/seed/idt_org/200/200',
			likedPercent: 97,
			hostedEvents: 3,
			hostingMonths: 6,
		},
		faqEntries: [
			{ id: 'f1', question: 'Is this the real Tomorrowland experience?', answer: 'Yes! This is an official Tomorrowland edition with the same stages, production design, and lineup quality as the Belgian original.' },
			{ id: 'f2', question: 'Are multi-day passes available?', answer: 'Yes, full festival passes (3-day) offer the best value. Single-day tickets are also available per stage.' },
			{ id: 'f3', question: 'What should I bring?', answer: 'Bring your e-ticket, a valid photo ID, comfortable shoes, and a reusable water bottle. Cashless payments accepted inside.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
		sale_timeline: [
			{ id: 'st1', label: 'DreamVille Pre-sale', dateRange: 'Tue 15 Apr, 12 PM – Thu 17 Apr, 12 PM', status: 'completed' },
			{ id: 'st2', label: 'General Sale', dateRange: 'Fri 18 Apr, 12 PM onwards', status: 'active' },
			{ id: 'st3', label: 'VIP Packages', dateRange: 'Mon 21 Apr, 10 AM onwards', status: 'upcoming' },
		],
	},
	{
		id: "e1b2c3d4-0007-0007-0007-000000000007",
		title: "Sunburn Arena ft. Alan Walker",
		description:
			"The global EDM icon returns to India for an unforgettable arena experience. Expect stunning visuals, iconic drops, and an electric crowd in one of India's premier concert venues.",
		status: "live",
		coverImage: "https://picsum.photos/seed/chappelle/800/500",
		date: "2026-09-15",
		time: "18:00",
		end_time: "23:00",
		isPromoted: false,
		venue_name: "Jio World Garden",
		venue_address: "G Block, Bandra Kurla Complex, Mumbai, Maharashtra 400051",
		city_name: "Mumbai",
		city: "mumbai",
		price_min: 1500,
		price_max: 5000,
		currency: "INR",
		is_wishlisted: true,
		event_type: "single_day",
		availability: "filling_fast",
		categories: ["Music", "Nightlife"],
		subCategory: "dj_night",
		languages: ["english"],
		amenities: ["Parking", "Food Court", "Restrooms", "First Aid", "ATM", "Charging Station"],
		prohibited_items: ["Outside Food", "Glass Bottles", "Cameras"],
		seating_type: "non_seated",
		artist_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567801",
		media_images: [
			"https://picsum.photos/seed/walker1/800/600",
			"https://picsum.photos/seed/walker2/800/600",
		],
		venue_distance_km: 11.3,
		schedule_items: [
			{ label: 'Gates open', time: '6:00 PM' },
			{ label: 'Support act', time: '7:00 PM' },
			{ label: 'Alan Walker', time: '8:30 PM' },
			{ label: 'Event ends', time: '11:00 PM' },
		],
		highlights: [
			{ id: 'h1', icon: '🎧', title: 'Global EDM icon live', description: 'The masked maestro behind "Faded" brings his iconic sound to India.' },
			{ id: 'h2', icon: '💡', title: 'Arena-scale production', description: 'State-of-the-art LED visuals and laser show at Jio World Garden.' },
		],
		artists_detail: [
			{
				id: 'a_walker',
				name: 'Alan Walker',
				role: 'Norwegian DJ and record producer',
				image: 'https://picsum.photos/seed/walker_art/400/400',
				bio: 'Alan Walker is a Norwegian DJ, record producer, and music video director. He rose to international fame with the single "Faded" in 2015. Known for his signature mask and hoodie look, Walker blends electronic music with cinematic elements for a unique live experience.',
				instagramFollowers: '22M',
				youtubeSubscribers: '48M',
			},
		],
		about: 'The global EDM icon returns to India for a spectacular arena show at the iconic Jio World Garden.\n\nExpect stunning LED visuals, laser shows, iconic drops from "Faded", "Alone", and "Darkside", plus his newest releases performed live for the first time in India.\n\nSunburn Arena presents India\'s most anticipated electronic music show of the year. Tickets are selling fast — don\'t miss out.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Event in English' },
			{ iconName: 'Users', label: 'Ages 16 and above recommended' },
			{ iconName: 'PawPrint', label: 'Pets not allowed' },
			{ iconName: 'Camera', label: 'Professional cameras not allowed' },
			{ iconName: 'Zap', label: 'Charging stations available' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Utensils', label: 'Food & beverages on sale' },
			{ iconName: 'Shield', label: 'First aid on site' },
			{ iconName: 'CreditCard', label: 'ATM on site' },
			{ iconName: 'Zap', label: 'Charging stations' },
		],
		gallery_urls: [
			'https://picsum.photos/seed/walker_g1/600/600',
			'https://picsum.photos/seed/walker_g2/600/600',
			'https://picsum.photos/seed/walker_g3/600/600',
			'https://picsum.photos/seed/walker_g4/600/600',
		],
		organiser_detail: {
			name: 'Sunburn Entertainment',
			logoUrl: 'https://picsum.photos/seed/sunburn_org/200/200',
			likedPercent: 89,
			hostedEvents: 14,
			hostingMonths: 48,
		},
		faqEntries: [
			{ id: 'f1', question: 'What time does Alan Walker perform?', answer: 'Alan Walker takes the stage at 8:30 PM and performs until 11:00 PM.' },
			{ id: 'f2', question: 'Is re-entry allowed?', answer: 'No re-entry is permitted once you exit the venue.' },
			{ id: 'f3', question: 'Are there any age restrictions?', answer: 'The event is open to all ages, but 16+ is recommended given the crowd intensity.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
		sale_timeline: [
			{ id: 'st1', label: 'Presale', dateRange: 'Mon 25 May, 10 AM – Wed 27 May, 10 PM', status: 'completed' },
			{ id: 'st2', label: 'General Sale', dateRange: 'Thu 28 May, 10 AM onwards', status: 'active' },
		],
	},
	{
		id: "e1b2c3d4-0008-0008-0008-000000000008",
		title: "Zakir Khan Live",
		description:
			'Catch the "Sakht Launda" live as he brings his signature storytelling and heartfelt comedy. An evening of laughter, nostalgia, and relatable observations about modern Indian life.',
		status: "live",
		coverImage: "https://picsum.photos/seed/zakirkhan/800/500",
		date: "2026-08-02",
		time: "19:30",
		end_time: "21:30",
		isPromoted: false,
		venue_name: "Siri Fort Auditorium",
		venue_address: "August Kranti Marg, Siri Institutional Area, New Delhi 110049",
		city_name: "Delhi",
		city: "delhi",
		price_min: 999,
		price_max: 2999,
		currency: "INR",
		is_wishlisted: false,
		event_type: "single_day",
		availability: "available",
		categories: ["Comedy", "Performances"],
		subCategory: "standup",
		languages: ["hindi"],
		amenities: ["Parking", "Restrooms", "Wheelchair Access"],
		prohibited_items: ["Outside Food", "Cameras"],
		seating_type: "seated",
		artist_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567803",
		media_images: [
			"https://picsum.photos/seed/zakir1/800/600",
			"https://picsum.photos/seed/zakir2/800/600",
		],
		venue_distance_km: 6.7,
		schedule_items: [
			{ label: 'Doors open', time: '6:30 PM' },
			{ label: 'Show starts', time: '7:30 PM' },
			{ label: 'Show ends', time: '9:30 PM' },
		],
		highlights: [
			{ id: 'h1', icon: '😂', title: 'India\'s most beloved comedian', description: 'The "Sakht Launda" brings his new hour of storytelling and relatable Indian-life comedy.' },
			{ id: 'h2', icon: '🎤', title: 'Intimate venue experience', description: 'Siri Fort\'s intimate setting makes this show a special, up-close experience.' },
		],
		artists_detail: [
			{
				id: 'a_zakir',
				name: 'Zakir Khan',
				role: 'Stand-up comedian, writer, actor',
				image: 'https://picsum.photos/seed/zakir_art/400/400',
				bio: 'Zakir Khan is an Indian stand-up comedian, known for his character "Sakht Launda" and his heartfelt, story-based comedy about middle-class Indian life. He rose to fame on the Amazon Prime show Comicstaan and has sold out venues across India and internationally.',
				instagramFollowers: '8.1M',
				youtubeSubscribers: '6M',
			},
		],
		about: 'Catch Zakir Khan live as he brings his latest hour of heartfelt comedy and storytelling to Delhi.\n\nKnown for his iconic "Sakht Launda" persona and deeply relatable observations about modern Indian life, Zakir\'s shows are as much emotional as they are hilarious.\n\nThis intimate show at Siri Fort Auditorium promises to be an unforgettable evening of laughter, nostalgia, and raw human connection.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Show will be in Hindi' },
			{ iconName: 'Users', label: 'Recommended for ages 16 and above' },
			{ iconName: 'Clock', label: 'Duration: approximately 2 hours' },
			{ iconName: 'Accessibility', label: 'Wheelchair accessible venue' },
			{ iconName: 'Camera', label: 'Recording not permitted' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Accessibility', label: 'Wheelchair accessible' },
		],
		gallery_urls: [],
		organiser_detail: {
			name: 'OML Entertainment',
			logoUrl: 'https://picsum.photos/seed/oml_org/200/200',
			likedPercent: 91,
			hostedEvents: 38,
			hostingMonths: 30,
		},
		faqEntries: [
			{ id: 'f1', question: 'What language is the show in?', answer: 'The show is primarily in Hindi with some English phrases.' },
			{ id: 'f2', question: 'Is recording allowed?', answer: 'Recording or streaming of the show is strictly not permitted.' },
			{ id: 'f3', question: 'Is there a dress code?', answer: 'No dress code. Come as you are.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
	},
	{
		id: "e1b2c3d4-0009-0009-0009-000000000009",
		title: "A.R. Rahman: Harmony Live in Concert",
		description:
			"Experience the magic of the Mozart of Madras live with a full orchestra and choir. An evening celebrating 30 years of soul-stirring music from India's most celebrated composer.",
		status: "live",
		coverImage: "https://picsum.photos/seed/arrahman/800/500",
		date: "2026-11-20",
		time: "19:00",
		end_time: "22:00",
		isPromoted: false,
		venue_name: "Jawaharlal Nehru Stadium",
		venue_address: "Jawaharlal Nehru Stadium, Lodhi Road, New Delhi 110003",
		city_name: "Delhi",
		city: "delhi",
		price_min: 2000,
		price_max: 15000,
		currency: "INR",
		is_wishlisted: true,
		event_type: "single_day",
		availability: "sold_out",
		categories: ["Music", "Performances"],
		subCategory: "live_band",
		languages: ["hindi", "tamil", "english"],
		amenities: ["Parking", "Food Court", "Restrooms", "First Aid", "Wheelchair Access"],
		prohibited_items: ["Outside Food", "Glass Bottles", "Cameras"],
		seating_type: "seated",
		artist_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567806",
		media_images: [
			"https://picsum.photos/seed/arrahman1/800/600",
			"https://picsum.photos/seed/arrahman2/800/600",
		],
		venue_distance_km: 9.1,
		schedule_items: [
			{ label: 'Gates open', time: '5:30 PM' },
			{ label: 'Orchestra begins', time: '7:00 PM' },
			{ label: 'A.R. Rahman', time: '7:30 PM' },
			{ label: 'Concert ends', time: '10:00 PM' },
		],
		highlights: [
			{ id: 'h1', icon: '🎼', title: '30 years of music', description: 'A full orchestra and 50-voice choir celebrate three decades of A.R. Rahman\'s iconic compositions.' },
			{ id: 'h2', icon: '🏆', title: 'Double Oscar winner', description: 'Experience the genius behind Slumdog Millionaire live on stage with a world-class production.' },
		],
		artists_detail: [
			{
				id: 'a_arrahman',
				name: 'A.R. Rahman',
				role: 'Composer, singer, music producer',
				image: 'https://picsum.photos/seed/arrahman_art/400/400',
				bio: 'Allah Rakha Rahman, known as A.R. Rahman, is an Indian composer, singer, and music producer. He has won two Academy Awards, two Grammy Awards, a BAFTA Award, and a Golden Globe Award. His music has crossed all language and cultural barriers to become truly universal.',
				instagramFollowers: '12.3M',
				youtubeSubscribers: '9M',
			},
		],
		about: 'Experience the magic of the Mozart of Madras live with a full 80-piece orchestra and 50-voice choir.\n\nHarmony Live in Concert celebrates 30 years of A.R. Rahman\'s soul-stirring music — from Roja and Bombay to Slumdog Millionaire and beyond. Performed in Hindi, Tamil, and English, this concert transcends language.\n\nThis sold-out show is considered one of the most anticipated cultural events of 2026. Join 40,000 fans for a night that will move you to your core.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Show in Hindi, Tamil and English' },
			{ iconName: 'Users', label: 'All ages welcome' },
			{ iconName: 'Accessibility', label: 'Wheelchair accessible venue' },
			{ iconName: 'Camera', label: 'Professional cameras not permitted' },
			{ iconName: 'PawPrint', label: 'Pets not allowed' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Utensils', label: 'Food court inside' },
			{ iconName: 'Shield', label: 'First aid on site' },
			{ iconName: 'Accessibility', label: 'Wheelchair accessible' },
		],
		gallery_urls: [
			'https://picsum.photos/seed/arrahman_g1/600/600',
			'https://picsum.photos/seed/arrahman_g2/600/600',
			'https://picsum.photos/seed/arrahman_g3/600/600',
			'https://picsum.photos/seed/arrahman_g4/600/600',
		],
		organiser_detail: {
			name: 'Wizcraft International',
			logoUrl: 'https://picsum.photos/seed/wizcraft_org/200/200',
			likedPercent: 93,
			hostedEvents: 52,
			hostingMonths: 60,
		},
		faqEntries: [
			{ id: 'f1', question: 'Which songs will be performed?', answer: 'The setlist spans all of A.R. Rahman\'s celebrated works across Hindi, Tamil, and English films. Specific songs will not be revealed in advance.' },
			{ id: 'f2', question: 'Is the concert sold out?', answer: 'Yes, all ticket categories are sold out. Monitor the app for any returned tickets.' },
			{ id: 'f3', question: 'Is seating allocated?', answer: 'Yes, this is a fully seated show with allocated seating as per ticket category.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'sold_out',
	},
	{
		id: "e1b2c3d4-0010-0010-0010-000000000010",
		title: "Vir Das: Mind Fool India Tour",
		description:
			"Vir Das is back with a razor-sharp new hour that dissects politics, culture, and the beautiful chaos of being Indian. The most anticipated standup special of 2026 hits multiple cities.",
		status: "live",
		coverImage: "https://picsum.photos/seed/virdas/800/500",
		date: "2026-07-25",
		time: "20:00",
		end_time: "21:45",
		isPromoted: false,
		venue_name: "St. Andrews Auditorium",
		venue_address: "St. Andrews College Campus, Bandra West, Mumbai 400050",
		city_name: "Mumbai",
		city: "mumbai",
		price_min: 799,
		price_max: 3500,
		currency: "INR",
		is_wishlisted: false,
		event_type: "single_day",
		availability: "available",
		categories: ["Comedy", "Performances"],
		subCategory: "comedy_special",
		languages: ["english", "hindi"],
		amenities: ["Parking", "Restrooms", "Wi-Fi"],
		prohibited_items: ["Outside Food", "Cameras"],
		seating_type: "seated",
		artist_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567807",
		media_images: [
			"https://picsum.photos/seed/virdas1/800/600",
			"https://picsum.photos/seed/virdas2/800/600",
		],
		venue_distance_km: 3.2,
		schedule_items: [
			{ label: 'Doors open', time: '7:00 PM' },
			{ label: 'Show starts', time: '8:00 PM' },
			{ label: 'Show ends', time: '9:45 PM' },
		],
		highlights: [
			{ id: 'h1', icon: '🇮🇳', title: 'India\'s global comedy voice', description: 'Vir Das — Netflix special comedian and global touring artist — returns to Mumbai.' },
			{ id: 'h2', icon: '🔥', title: 'A razor-sharp new hour', description: 'Mind Fool dissects politics, culture, and the chaos of being Indian like never before.' },
		],
		artists_detail: [
			{
				id: 'a_virdas',
				name: 'Vir Das',
				role: 'Stand-up comedian, actor, writer',
				image: 'https://picsum.photos/seed/virdas_art/400/400',
				bio: 'Vir Das is an Indian-American stand-up comedian, actor, and author. He has six Netflix specials, has performed at the Kennedy Center and Carnegie Hall, and is the first Indian comedian to be Emmy-nominated. Mind Fool is his most ambitious and politically charged show to date.',
				instagramFollowers: '3.2M',
				youtubeSubscribers: '2M',
			},
		],
		about: 'Vir Das is back with a razor-sharp new hour — Mind Fool.\n\nHaving conquered Netflix, Carnegie Hall, and the Emmy nominations, India\'s most globally recognized comedian returns home to dissect politics, culture, and the beautiful, chaotic madness of being Indian in 2026.\n\nThis is bilingual comedy that will make you laugh, think, and question everything. Catch it at St. Andrews Auditorium — Vir Das\'s favorite intimate venue in Mumbai.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Show in English and Hindi' },
			{ iconName: 'Users', label: 'Recommended for ages 18 and above' },
			{ iconName: 'Clock', label: 'Duration: approximately 1 hour 45 minutes' },
			{ iconName: 'Camera', label: 'Recording strictly prohibited' },
			{ iconName: 'Wifi', label: 'Wi-Fi available in venue' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Wifi', label: 'Wi-Fi available' },
		],
		gallery_urls: [],
		organiser_detail: {
			name: 'Weirdass Comedy',
			logoUrl: 'https://picsum.photos/seed/weirdass_org/200/200',
			likedPercent: 90,
			hostedEvents: 19,
			hostingMonths: 18,
		},
		faqEntries: [
			{ id: 'f1', question: 'Is the show suitable for all ages?', answer: 'The show contains adult themes and strong language. Recommended for 18 and above.' },
			{ id: 'f2', question: 'Can I record the show?', answer: 'No. Recording, streaming, or photographing the show is strictly prohibited.' },
			{ id: 'f3', question: 'Will there be a meet and greet?', answer: 'There is no formal meet and greet. Vir may interact briefly with the audience post-show.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
	},
	{
		id: "e1b2c3d4-0011-0011-0011-000000000011",
		title: "Bengaluru Food & Drinks Festival 2026",
		description:
			"Three days celebrating the best of Bengaluru's thriving food and craft beverage scene. Over 80 restaurants, 30 craft breweries, live cooking demos, and celebrity chef masterclasses.",
		status: "live",
		coverImage: "https://picsum.photos/seed/foodfest/800/500",
		date: "2026-09-05",
		end_date: "2026-09-07",
		time: "12:00",
		end_time: "22:00",
		isPromoted: true,
		venue_name: "Lalbagh Botanical Garden",
		venue_address: "Mavalli, Bengaluru, Karnataka 560004",
		city_name: "Bengaluru",
		city: "bengaluru",
		price_min: 299,
		price_max: 1499,
		currency: "INR",
		is_wishlisted: false,
		event_type: "multi_day",
		availability: "available",
		categories: ["Food & Drink", "Fests & Fairs"],
		subCategory: "food_festival",
		languages: ["english", "kannada"],
		amenities: ["Parking", "First Aid", "Restrooms", "Water Station", "ATM"],
		cover_charge: "",
		prohibited_items: ["Outside Food", "Glass Bottles", "Pets"],
		seating_type: "non_seated",
		instagramUrl: "https://instagram.com/bengalurufoodanddinks",
		media_images: [
			"https://picsum.photos/seed/foodfest1/800/600",
			"https://picsum.photos/seed/foodfest2/800/600",
		],
		venue_distance_km: 7.5,
		schedule_items: [
			{ label: 'Festival opens', time: '12:00 PM' },
			{ label: 'Chef masterclasses', time: '2:00 PM' },
			{ label: 'Live music begins', time: '6:00 PM' },
			{ label: 'Festival closes', time: '10:00 PM' },
		],
		highlights: [
			{ id: 'h1', icon: '🍺', title: '30 craft breweries', description: 'Bengaluru\'s finest craft beer scene all in one place — tastings, pairings, and brewery tours.' },
			{ id: 'h2', icon: '👨‍🍳', title: 'Celebrity chef masterclasses', description: 'Learn from India\'s top chefs in exclusive hands-on cooking masterclasses.' },
		],
		artists_detail: [
			{
				id: 'a_chef1',
				name: 'Chef Ranveer Brar',
				role: 'Celebrity chef, restaurateur, TV host',
				image: 'https://picsum.photos/seed/ranveer_art/400/400',
				bio: 'Ranveer Brar is an Indian celebrity chef, restaurateur, food stylist, and TV host. Best known for hosting MasterChef India, he will lead a live cooking masterclass showcasing modern Indian cuisine at the festival.',
				instagramFollowers: '4.5M',
			},
		],
		about: 'Three days celebrating the very best of Bengaluru\'s world-class food and craft beverage scene.\n\nOver 80 restaurants, 30 craft breweries, celebrity chef masterclasses, live cooking demos, wine tastings, and live music performances — the Bengaluru Food & Drinks Festival is a foodie\'s paradise.\n\nSet in the stunning Lalbagh Botanical Garden, this is the most unique food festival in India. Come hungry, leave inspired.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Event in English and Kannada' },
			{ iconName: 'Users', label: 'All ages welcome' },
			{ iconName: 'Ticket', label: 'Entry ticket required. Food purchased separately.' },
			{ iconName: 'PawPrint', label: 'Pets not allowed' },
			{ iconName: 'Droplets', label: 'Drinking water available' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Shield', label: 'First aid on site' },
			{ iconName: 'Droplets', label: 'Water stations' },
			{ iconName: 'CreditCard', label: 'ATM on site' },
		],
		gallery_urls: [
			'https://picsum.photos/seed/food_g1/600/600',
			'https://picsum.photos/seed/food_g2/600/600',
			'https://picsum.photos/seed/food_g3/600/600',
			'https://picsum.photos/seed/food_g4/600/600',
		],
		organiser_detail: {
			name: 'Paytm Insider Events',
			logoUrl: 'https://picsum.photos/seed/insider_org/200/200',
			likedPercent: 87,
			hostedEvents: 31,
			hostingMonths: 28,
		},
		faqEntries: [
			{ id: 'f1', question: 'Is food included in the ticket price?', answer: 'No. Entry ticket covers access to the festival. Food and drinks are purchased separately from individual stalls.' },
			{ id: 'f2', question: 'Are masterclass spots limited?', answer: 'Yes. Masterclass spots are limited and first-come-first-served. Arrive early to secure your spot.' },
			{ id: 'f3', question: 'Can children attend?', answer: 'Yes, the festival is family-friendly. Children below 5 enter free.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
	},
	{
		id: "e1b2c3d4-0012-0012-0012-000000000012",
		title: "Gully Gang Open Mic Night",
		description:
			"Mumbai's biggest open mic night returns — an evening of raw, unfiltered comedy by emerging voices from the city. Hosted by Comicstaan fame Rahul Subramanian.",
		status: "live",
		coverImage: "https://picsum.photos/seed/openmic/800/500",
		date: "2026-08-15",
		time: "19:00",
		end_time: "22:00",
		isPromoted: false,
		venue_name: "The Comedy Store",
		venue_address: "Palladium Mall Level 4, Lower Parel, Mumbai 400013",
		city_name: "Mumbai",
		city: "mumbai",
		price_min: 299,
		price_max: 799,
		currency: "INR",
		is_wishlisted: false,
		event_type: "single_day",
		availability: "available",
		categories: ["Comedy", "Nightlife"],
		subCategory: "open_mic",
		languages: ["english", "hindi"],
		amenities: ["Restrooms", "Wi-Fi"],
		cover_charge: "200",
		prohibited_items: ["Outside Food"],
		seating_type: "seated",
		media_images: [
			"https://picsum.photos/seed/openmic1/800/600",
		],
		venue_distance_km: 5.8,
		schedule_items: [
			{ label: 'Doors open', time: '6:30 PM' },
			{ label: 'Open mic starts', time: '7:00 PM' },
			{ label: 'Headliner set', time: '9:30 PM' },
			{ label: 'Show ends', time: '10:00 PM' },
		],
		highlights: [
			{ id: 'h1', icon: '🎤', title: 'Mumbai\'s biggest open mic', description: 'Discover the next big voice in Indian comedy at the city\'s most celebrated open mic night.' },
			{ id: 'h2', icon: '⭐', title: 'Hosted by Rahul Subramanian', description: 'Comicstaan season 2 winner hosts an evening of unfiltered, raw comedy.' },
		],
		artists_detail: [
			{
				id: 'a_rahul',
				name: 'Rahul Subramanian',
				role: 'Stand-up comedian, Comicstaan winner',
				image: 'https://picsum.photos/seed/rahul_art/400/400',
				bio: 'Rahul Subramanian is an Indian stand-up comedian and winner of Comicstaan Season 2. Known for his clean, intelligent, and hilarious observational comedy, he has sold out shows across India and is one of the most in-demand comics in the country.',
				instagramFollowers: '1.8M',
				youtubeSubscribers: '1.2M',
			},
		],
		about: 'Mumbai\'s biggest open mic night returns to The Comedy Store at Palladium.\n\nAn evening of raw, unfiltered comedy from Mumbai\'s best emerging voices, hosted by Comicstaan Season 2 winner Rahul Subramanian. Watch comedy being made in real time — some of these performers will be the stars of tomorrow.\n\nA cover charge applies at the door. Grab a drink, take a seat, and enjoy a night of laughter.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Show in English and Hindi' },
			{ iconName: 'Users', label: 'Recommended for ages 18 and above' },
			{ iconName: 'Wifi', label: 'Wi-Fi available' },
			{ iconName: 'Camera', label: 'Recording not permitted' },
		],
		things_to_know_amenities: [
			{ iconName: 'Wifi', label: 'Wi-Fi available' },
		],
		gallery_urls: [],
		organiser_detail: {
			name: 'Gully Gang Comedy',
			logoUrl: 'https://picsum.photos/seed/gully_org/200/200',
			likedPercent: 86,
			hostedEvents: 12,
			hostingMonths: 8,
		},
		faqEntries: [
			{ id: 'f1', question: 'Is there a cover charge on top of the ticket?', answer: 'Yes, there is a ₹200 cover charge at the door, separate from your entry ticket.' },
			{ id: 'f2', question: 'Can I sign up to perform?', answer: 'Yes! DM @gullygangcomedy on Instagram to register for an open mic slot. Spots are limited.' },
			{ id: 'f3', question: 'Is there a drink minimum?', answer: 'There is no drink minimum, but beverages are available for purchase at the bar.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
	},
	{
		id: "e1b2c3d4-0013-0013-0013-000000000013",
		title: "IPL 2026: MI vs RCB",
		description:
			"The ultimate rivalry in Indian cricket — Mumbai Indians take on Royal Challengers Bengaluru in a do-or-die league match at the iconic Wankhede Stadium. Blue sea vs. red army.",
		status: "live",
		coverImage: "https://picsum.photos/seed/iplcricket/800/500",
		date: "2026-04-18",
		time: "19:30",
		end_time: "23:30",
		isPromoted: true,
		venue_name: "Wankhede Stadium",
		venue_address: "D Road, Churchgate, Mumbai, Maharashtra 400020",
		city_name: "Mumbai",
		city: "mumbai",
		price_min: 500,
		price_max: 8000,
		currency: "INR",
		is_wishlisted: true,
		event_type: "single_day",
		availability: "filling_fast",
		categories: ["Sports"],
		subCategory: "cricket",
		languages: ["hindi", "english"],
		amenities: ["Parking", "Food Court", "Restrooms", "First Aid", "ATM"],
		prohibited_items: ["Glass Bottles", "Drones", "Laser Pointers", "Outside Food"],
		seating_type: "seated",
		media_images: [
			"https://picsum.photos/seed/ipl1/800/600",
			"https://picsum.photos/seed/ipl2/800/600",
		],
		venue_distance_km: 2.1,
		schedule_items: [
			{ label: 'Gates open', time: '5:00 PM' },
			{ label: 'Toss', time: '7:00 PM' },
			{ label: 'Match begins', time: '7:30 PM' },
			{ label: 'Estimated end', time: '11:30 PM' },
		],
		highlights: [
			{ id: 'h1', icon: '🏏', title: 'The biggest rivalry in IPL', description: 'MI vs RCB — the most watched match-up in IPL history comes to Wankhede.' },
			{ id: 'h2', icon: '🔵', title: 'Blue sea at Wankhede', description: 'Experience the electric atmosphere of a sold-out Wankhede with 33,000 fans.' },
		],
		artists_detail: [
			{
				id: 'a_rohit',
				name: 'Rohit Sharma',
				role: 'Mumbai Indians Captain',
				image: 'https://picsum.photos/seed/rohit_art/400/400',
				bio: 'Rohit Sharma is the captain of Mumbai Indians and a legendary Indian cricketer. Known as the "Hitman", he holds the record for the most centuries in ODI cricket and has led MI to five IPL titles.',
			},
			{
				id: 'a_kohli',
				name: 'Virat Kohli',
				role: 'Royal Challengers Bengaluru',
				image: 'https://picsum.photos/seed/kohli_art/400/400',
				bio: 'Virat Kohli is one of the greatest batsmen of all time and the face of Royal Challengers Bengaluru. His passion and intensity make MI vs RCB the most anticipated match of every IPL season.',
				instagramFollowers: '265M',
			},
		],
		about: 'The ultimate rivalry in Indian cricket returns to the iconic Wankhede Stadium.\n\nMumbai Indians vs Royal Challengers Bengaluru is not just a cricket match — it\'s a cultural event. With 33,000 passionate fans, electric atmosphere, and the chance to see India\'s greatest players in action, this is the match of the season.\n\nGrab your tickets before they sell out. The blue sea at Wankhede awaits.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Commentary in Hindi and English' },
			{ iconName: 'Users', label: 'All ages welcome' },
			{ iconName: 'Ticket', label: 'Ticket required for ages 3 and above' },
			{ iconName: 'Shield', label: 'Security check at entry — arrive early' },
			{ iconName: 'PawPrint', label: 'Pets not allowed' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Utensils', label: 'Food court inside' },
			{ iconName: 'Shield', label: 'First aid on site' },
			{ iconName: 'CreditCard', label: 'ATM on site' },
		],
		gallery_urls: [
			'https://picsum.photos/seed/ipl_g1/600/600',
			'https://picsum.photos/seed/ipl_g2/600/600',
			'https://picsum.photos/seed/ipl_g3/600/600',
			'https://picsum.photos/seed/ipl_g4/600/600',
		],
		organiser_detail: {
			name: 'BCCI & IPL',
			logoUrl: 'https://picsum.photos/seed/bcci_org/200/200',
			likedPercent: 96,
			hostedEvents: 120,
			hostingMonths: 96,
		},
		faqEntries: [
			{ id: 'f1', question: 'What time should I arrive?', answer: 'Gates open at 5:00 PM. We recommend arriving at least 1 hour before the toss to clear security checks.' },
			{ id: 'f2', question: 'What items are prohibited?', answer: 'Glass bottles, drones, laser pointers, and outside food are not permitted. Full list available at the venue website.' },
			{ id: 'f3', question: 'What happens if there is rain?', answer: 'In case of rain, the match may be shortened using the DLS method. Tickets are non-refundable for weather interruptions.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
	},
	{
		id: "e1b2c3d4-0014-0014-0014-000000000014",
		title: "Ashtanga Yoga & Wellness Retreat",
		description:
			"A two-day immersive yoga and wellness retreat led by international instructors. Includes guided Ashtanga sessions, breathwork, meditation, Ayurvedic nutrition workshops, and sound healing.",
		status: "live",
		coverImage: "https://picsum.photos/seed/yoga/800/500",
		date: "2026-08-22",
		end_date: "2026-08-23",
		time: "07:00",
		end_time: "17:00",
		isPromoted: false,
		venue_name: "The Yoga House",
		venue_tba: false,
		venue_address: "Hill Road, Bandra West, Mumbai, Maharashtra 400050",
		city_name: "Mumbai",
		city: "mumbai",
		price_min: 2500,
		price_max: 6000,
		currency: "INR",
		is_wishlisted: false,
		event_type: "multi_day",
		availability: "available",
		categories: ["Fitness"],
		subCategory: "wellness",
		languages: ["english"],
		amenities: ["Parking", "Restrooms", "Water Station", "Wi-Fi"],
		prohibited_items: ["Smoking", "Alcohol", "Pets"],
		seating_type: "non_seated",
		media_images: [
			"https://picsum.photos/seed/yoga1/800/600",
		],
		venue_distance_km: 4.0,
		schedule_items: [
			{ label: 'Registration & check-in', time: '6:30 AM' },
			{ label: 'Morning Ashtanga session', time: '7:00 AM' },
			{ label: 'Pranayama & meditation', time: '10:00 AM' },
			{ label: 'Afternoon workshops', time: '2:00 PM' },
			{ label: 'Closing ceremony', time: '5:00 PM' },
		],
		highlights: [
			{ id: 'h1', icon: '🧘', title: 'Led by international instructors', description: 'Certified Ashtanga instructors from Mysore and London guide sessions for all levels.' },
			{ id: 'h2', icon: '🌿', title: 'Holistic wellness experience', description: 'Yoga, breathwork, sound healing, Ayurvedic nutrition — a complete mind-body retreat.' },
		],
		artists_detail: [
			{
				id: 'a_yoga',
				name: 'Kavita Mehra',
				role: 'Certified Ashtanga instructor, wellness coach',
				image: 'https://picsum.photos/seed/yoga_art/400/400',
				bio: 'Kavita Mehra is a Mysore-trained Ashtanga yoga instructor with 15 years of teaching experience. She has led retreats across India, Bali, and London. She specializes in making Ashtanga accessible to practitioners of all levels while preserving its authentic tradition.',
			},
		],
		about: 'A two-day immersive yoga and wellness retreat at The Yoga House, Bandra.\n\nLed by internationally certified Ashtanga instructors, this retreat includes guided morning Ashtanga sessions, pranayama, meditation, Ayurvedic nutrition workshops, and a closing sound healing ceremony.\n\nDesigned for practitioners of all levels — beginners welcome. Escape the city, reconnect with your body, and return renewed.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Retreat conducted in English' },
			{ iconName: 'Users', label: 'Open to all experience levels' },
			{ iconName: 'Shirt', label: 'Wear comfortable yoga attire' },
			{ iconName: 'Droplets', label: 'Bring your own water bottle and yoga mat' },
			{ iconName: 'Wifi', label: 'Wi-Fi available' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Droplets', label: 'Water stations' },
			{ iconName: 'Wifi', label: 'Wi-Fi available' },
		],
		gallery_urls: [],
		organiser_detail: {
			name: 'The Yoga House',
			logoUrl: 'https://picsum.photos/seed/yogahouse_org/200/200',
			likedPercent: 95,
			hostedEvents: 8,
			hostingMonths: 12,
		},
		faqEntries: [
			{ id: 'f1', question: 'Do I need prior yoga experience?', answer: 'No. The retreat is designed for all levels, from complete beginners to advanced practitioners.' },
			{ id: 'f2', question: 'What should I bring?', answer: 'Bring a yoga mat, comfortable clothes, water bottle, and an open mind. All other props are provided.' },
			{ id: 'f3', question: 'Is food provided?', answer: 'Yes. Sattvic (yogic) meals and refreshments are included on both days.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
	},
	{
		id: "e1b2c3d4-0015-0015-0015-000000000015",
		title: "Hyderabad Art Week 2026",
		description:
			"A week-long celebration of contemporary South Asian art featuring over 50 artists from across India, Pakistan, Sri Lanka, and Bangladesh. Curated exhibitions, live installations, and artist talks.",
		status: "live",
		coverImage: "https://picsum.photos/seed/artweek/800/500",
		date: "2026-10-01",
		end_date: "2026-10-07",
		time: "10:00",
		end_time: "20:00",
		isPromoted: false,
		venue_name: "Hyderabad International Convention Centre",
		venue_address: "Novotel & HICC Complex, Madhapur, Hyderabad, Telangana 500081",
		city_name: "Hyderabad",
		city: "hyderabad",
		price_min: 199,
		price_max: 999,
		currency: "INR",
		is_wishlisted: false,
		event_type: "multi_day",
		availability: "available",
		categories: ["Art Exhibitions"],
		subCategory: "art_exhibition",
		languages: ["english", "telugu", "hindi"],
		amenities: ["Parking", "Restrooms", "Wi-Fi", "Wheelchair Access", "ATM"],
		prohibited_items: ["Outside Food", "Pets"],
		seating_type: "non_seated",
		media_images: [
			"https://picsum.photos/seed/artweek1/800/600",
			"https://picsum.photos/seed/artweek2/800/600",
		],
		venue_distance_km: 9.4,
		schedule_items: [
			{ label: 'Exhibition opens', time: '10:00 AM' },
			{ label: 'Artist talks', time: '2:00 PM' },
			{ label: 'Evening events', time: '6:00 PM' },
			{ label: 'Exhibition closes', time: '8:00 PM' },
		],
		highlights: [
			{ id: 'h1', icon: '🎨', title: '50+ South Asian artists', description: 'Contemporary art from India, Pakistan, Sri Lanka, and Bangladesh in one landmark exhibition.' },
			{ id: 'h2', icon: '🗣️', title: 'Live artist talks', description: 'Daily artist-in-conversation sessions offer rare insight into the creative process.' },
		],
		artists_detail: [
			{
				id: 'a_art1',
				name: 'Bharti Kher',
				role: 'Contemporary artist, sculptor',
				image: 'https://picsum.photos/seed/bharti_art/400/400',
				bio: 'Bharti Kher is an internationally acclaimed British-Indian artist known for her sculptural works and installations that explore identity, feminism, and the post-colonial condition. Her work is held in major collections globally including the Tate Modern.',
			},
		],
		about: 'A week-long celebration of contemporary South Asian art at the Hyderabad International Convention Centre.\n\nHyderabad Art Week 2026 brings together 50+ artists from across South Asia for curated exhibitions, live installations, gallery talks, and workshops. Experience a cross-section of contemporary painting, sculpture, digital art, and performance art.\n\nA cultural moment for the region, this is the largest South Asian contemporary art event of the year.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Event in English, Telugu and Hindi' },
			{ iconName: 'Users', label: 'All ages welcome' },
			{ iconName: 'Accessibility', label: 'Wheelchair accessible venue' },
			{ iconName: 'Wifi', label: 'Wi-Fi available throughout' },
			{ iconName: 'PawPrint', label: 'Pets not allowed' },
		],
		things_to_know_amenities: [
			{ iconName: 'Car', label: 'Parking available' },
			{ iconName: 'Wifi', label: 'Wi-Fi available' },
			{ iconName: 'Accessibility', label: 'Wheelchair accessible' },
			{ iconName: 'CreditCard', label: 'ATM on site' },
		],
		gallery_urls: [
			'https://picsum.photos/seed/art_g1/600/600',
			'https://picsum.photos/seed/art_g2/600/600',
			'https://picsum.photos/seed/art_g3/600/600',
			'https://picsum.photos/seed/art_g4/600/600',
		],
		organiser_detail: {
			name: 'Hyderabad Arts Foundation',
			logoUrl: 'https://picsum.photos/seed/hyf_org/200/200',
			likedPercent: 88,
			hostedEvents: 7,
			hostingMonths: 24,
		},
		faqEntries: [
			{ id: 'f1', question: 'Is the same ticket valid for all 7 days?', answer: 'A 7-day pass gives access to all days. Single-day passes are also available for purchase.' },
			{ id: 'f2', question: 'Can I buy artwork at the exhibition?', answer: 'Yes, most works are available for purchase. Contact the gallery desk for pricing and acquisition inquiries.' },
			{ id: 'f3', question: 'Are children\'s programs available?', answer: 'Yes, weekend workshops for children aged 6-14 are available. Register separately at the venue.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
	},
	{
		id: "e1b2c3d4-0016-0016-0016-000000000016",
		title: "New Year's Eve Rooftop Party: Mumbai 2027",
		description:
			"Ring in 2027 in style at Mumbai's most exclusive rooftop NYE celebration. DJ sets, open bar, gourmet canapés, and a breathtaking view of the city skyline as the clock strikes midnight.",
		status: "live",
		coverImage: "https://picsum.photos/seed/newyearseve/800/500",
		date: "2026-12-31",
		time: "21:00",
		end_time: "03:00",
		isPromoted: true,
		venue_name: "Asilo at St. Regis",
		venue_tba: false,
		venue_address: "St. Regis Mumbai, 462 Senapati Bapat Marg, Lower Parel, Mumbai 400013",
		city_name: "Mumbai",
		city: "mumbai",
		price_min: 3500,
		price_max: 8000,
		currency: "INR",
		is_wishlisted: true,
		event_type: "single_day",
		availability: "filling_fast",
		categories: ["Nightlife", "Social Mixer"],
		subCategory: "rooftop",
		languages: ["english"],
		amenities: ["Restrooms", "Wi-Fi", "Charging Station"],
		cover_charge: "",
		prohibited_items: ["Outside Food", "Outside Alcohol"],
		seating_type: "non_seated",
		media_images: [
			"https://picsum.photos/seed/nye1/800/600",
			"https://picsum.photos/seed/nye2/800/600",
		],
		venue_distance_km: 6.5,
		schedule_items: [
			{ label: 'Doors open', time: '9:00 PM' },
			{ label: 'DJ sets begin', time: '9:30 PM' },
			{ label: 'Countdown & midnight toast', time: '11:55 PM' },
			{ label: 'After-party', time: '12:00 AM' },
		],
		highlights: [
			{ id: 'h1', icon: '🎆', title: 'Rooftop skyline countdown', description: 'Welcome 2027 with Mumbai\'s iconic skyline as your backdrop and an open bar in hand.' },
			{ id: 'h2', icon: '🍾', title: 'Open bar & gourmet bites', description: 'Premium open bar and gourmet canapés included in your ticket price.' },
		],
		artists_detail: [
			{
				id: 'a_dj_nye',
				name: 'DJ Nucleya',
				role: 'Electronic music producer, DJ',
				image: 'https://picsum.photos/seed/nucleya_art/400/400',
				bio: 'Nucleya is an Indian electronic music producer and DJ known for his unique blend of bass music with Indian classical influences. He is one of India\'s most-streamed electronic artists and a festival headliner across Asia.',
				instagramFollowers: '1.5M',
				youtubeSubscribers: '2.3M',
			},
		],
		about: 'Ring in 2027 at Mumbai\'s most exclusive rooftop New Year\'s Eve celebration at Asilo, St. Regis.\n\nEnjoy curated DJ sets by DJ Nucleya, a premium open bar, gourmet canapés, and a breathtaking 360° view of Mumbai\'s glittering skyline as the city counts down to midnight.\n\nTickets are strictly limited for this intimate rooftop experience. Dress to impress — this is New Year\'s Eve done right.',
		things_to_know_info: [
			{ iconName: 'Languages', label: 'Event in English' },
			{ iconName: 'Users', label: 'Ages 21 and above only' },
			{ iconName: 'Ticket', label: 'Valid ID with age proof required' },
			{ iconName: 'Shirt', label: 'Smart casual dress code enforced' },
			{ iconName: 'Wifi', label: 'Wi-Fi available' },
		],
		things_to_know_amenities: [
			{ iconName: 'Wifi', label: 'Wi-Fi available' },
			{ iconName: 'Zap', label: 'Charging stations' },
		],
		gallery_urls: [
			'https://picsum.photos/seed/nye_g1/600/600',
			'https://picsum.photos/seed/nye_g2/600/600',
			'https://picsum.photos/seed/nye_g3/600/600',
		],
		organiser_detail: {
			name: 'St. Regis Mumbai',
			logoUrl: 'https://picsum.photos/seed/stregis_org/200/200',
			likedPercent: 96,
			hostedEvents: 6,
			hostingMonths: 12,
		},
		faqEntries: [
			{ id: 'f1', question: 'Is the open bar truly unlimited?', answer: 'Yes. Your ticket includes unlimited standard spirits, beer, wine, and non-alcoholic beverages throughout the night.' },
			{ id: 'f2', question: 'Is there a dress code?', answer: 'Smart casual. No shorts, flip-flops, or sportswear. The venue reserves the right to deny entry for inappropriate attire.' },
			{ id: 'f3', question: 'How many guests will be there?', answer: 'This is an intimate rooftop event. The capacity is limited to 300 guests for an exclusive experience.' },
		],
		termsAndConditions: COMMON_TERMS.join('\n'),
		sale_status: 'general_sale',
	},
]
